### ISSUE TITLE
Outdated Login API

### ISSUE THREAD

**Issue by Valinwolf** [matrix-org/purple-matrix#100]
Purple Matrix still uses the old `/_matrix/client/api/v1/login` endpoint, making it incompatible with the Synapse alternative, Construct, which uses the newer APIs. Purple Matrix should move away from legacy APIs.

**Comment by penguin42** [comment]
Just to clarify, is it the r0/login that you're expecting?

**Comment by Valinwolf** [comment]
Correct

**Comment by penguin42** [comment]
Hi Valinwolf,
  Can you try:  https://github.com/penguin42/purple-matrix/tree/loginwork
(Actually just the first commit 'api/login: synapse got r0 login ' should do you)
