### ISSUE TITLE
'GParameter' is deprecated

### ISSUE THREAD

**Issue by ildar** [matrix-org/purple-matrix#101]
so with the default -Werror=deprecated-declarations build fails.

**Comment by penguin42** [comment]
Confirmed on Fedora 31

**Comment by penguin42** [comment]
Hmm, the problem here isn't actually purple-matrix; it's libpurple, it defines:

gboolean purple_media_add_stream(PurpleMedia *media, const gchar *sess_id,
    const gchar *who, PurpleMediaSessionType type,
    gboolean initiator, const gchar *transmitter,
    guint num_params, GParameter *params);

purple-matrix doesn't use that at all; but since it's in the header it gets moaned at.

**Comment by penguin42** [comment]
Filed on libpurple here:
https://developer.pidgin.im/ticket/17415

**Comment by ildar** [comment]
The problem with THIS plugin is `-Werror` in makefiles. Is it really
necessary?

**Comment by EionRobb** [comment]
Can you use G_DISABLE_DEPRECATED? 

Unfortunately we can't change the libpurple API due to semver, until 3.0, so it's always going to give off that warning.

**Comment by penguin42** [comment]
Yeh adding a -DGLIB_DISABLE_DEPRECATION_WARNINGS is probably the best fix for now I guess.

**Comment by T0MuX** [comment]
Hi, how do I compile with this option ? I did this but doesnt work :
`make -DGLIB_DISABLE_DEPRECATION_WARNINGS`

**Comment by teleshoes** [comment]
@T0MuX
edit CFLAGS in Makefile.common, either:

1) remove `-Werror` from line 5   (dont fail on warnings)
or
2) add a new line at line 7 (turn off warnings on deprecations):
e.g.:
`CFLAGS += -DGLIB_DISABLE_DEPRECATION_WARNINGS`

**Comment by penguin42** [comment]
Merged teleshoes addition of the -D; thanks.
