### ISSUE TITLE
Build failure because of uninitialized variable

### ISSUE THREAD

**Issue by PureTryOut** [matrix-org/purple-matrix#108]
I'm trying to build this on Alpine Linux but with latest commit it fails:

```
matrix-room.c: In function '_on_state_update':
matrix-room.c:220:32: error: 'old_user_ids' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  220 |         const gchar *user_id = json_array_get_string_element(old_user_ids, i);
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
matrix-room.c:201:16: note: 'old_user_ids' was declared here
  201 |     JsonArray *old_user_ids, *new_user_ids;
      |                ^~~~~~~~~~~~
```

**Comment by penguin42** [comment]
Which compiler was that? Your compiler needs to wake up and read the code :-)
the if at the top sets old_user_ids, the only case it doesn't it sets old_len=0 so that loop wont execute.

**Comment by PureTryOut** [comment]
Uh, some version of GCC, it's quite a while ago I reported this :thinking:, whatever was the latest GCC at time of reporting.

**Comment by penguin42** [comment]
If it doesn't happen for you any more I'd close it, since the compiler really shouldn't be that silly about it; if it still does we can add a work around.

**Comment by PureTryOut** [comment]
Nope, I can still reproduce it. I just rewrote the Alpine Linux APKBUILD for it and am now having the same compilation failure.

This is with GCC 10.3.1.

**Comment by penguin42** [comment]
Does this shut it up?

```

diff --git a/matrix-room.c b/matrix-room.c
index cd17ae7..040ab38 100644
--- a/matrix-room.c
+++ b/matrix-room.c
@@ -210,6 +210,7 @@ static void _on_typing(PurpleConversation *conv,
         old_user_ids = matrix_json_object_get_array_member(old_state->content, "user_ids");
         old_len = json_array_get_length(old_user_ids);
     } else {
+       old_user_ids = NULL; /* Work around gcc 10.3.1 false uninit warn */
         old_len = 0;
     }

```

**Comment by PureTryOut** [comment]
It does yes!

**Comment by penguin42** [comment]
ok, should be able to add that; but not until end of the week (if nothing else blows up....)

**Comment by PureTryOut** [comment]
I don't personally have a need for this software anymore so take your time :stuck_out_tongue_winking_eye:

**Comment by penguin42** [comment]
Hopefully fixed by https://github.com/matrix-org/purple-matrix/pull/118
