### ISSUE TITLE
Cannot receive encrypted messages.

### ISSUE THREAD

**Issue by Skaalgard** [matrix-org/purple-matrix#110]
On Pidgin, when other users send me encrypted direct messages, nothing shows up.

1. User sends encrypted DM to you.

Expected behavior:
Message is displayed in appropriate Pidgin conversation window.

 - OS: Linux Mint 19.2 Tina x86_64 
 - purple-matrix version 0.0.0+git20170530-1build1
 - Pidgin version 2.12.0

**Comment by sdgathman** [comment]
That's an ancient version of purple-matrix.  But even the 20191228 version still doesn't support encryption that I can see.

**Comment by richvdh** [comment]
Yes, it sounds like the problem there is an old version of the plugin.

As the README makes clear encryption is not implemented; decryption should work ok however.

**Comment by Skaalgard** [comment]
Okay, well then how do I install the newer version? The instructions clearly state that I should be installing from my repository, which I did.

**Comment by richvdh** [comment]
if you built from the latest master, I guess you do have the latest version.

**Comment by Skaalgard** [comment]
Well no, I installed it from my distro's repository, which is what your instructions told me to do. Should I install it another way to get the newer version?

**Comment by Skaalgard** [comment]
I built it from source, I'll see if that helps.

**Comment by richvdh** [comment]
oh right. perhaps you could open a PR to remove that bit of the readme. I can imagine that some distros are shipping old builds.
