### ISSUE TITLE
 Matrix rooms will not Enumerate in Pidgin's XMPP Service Discovery.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [matrix-org/purple-matrix#122]
Matrix rooms will not Enumerate in Pidgin's XMPP Service Discovery. This makes Matrix useless in Spectrum2.
I see no Rooms enumerated as XMPP Rooms, and I see no Matrix Contacts in Spectrum2.

**Comment by richvdh** [comment]
duplicate of #138
