### ISSUE TITLE
Is this still up to date?

### ISSUE THREAD

**Issue by pjz** [matrix-org/purple-matrix#13]
I built it and tried to use it, but I just got `Error from home server: M_FORBIDDEN:`

**Comment by richvdh** [comment]
Yes, it should still work.

as for the error: are you sure your credentials are correct? You can try running the below to get more information on the requests pidgin is making, but be careful with the log because it will contain your password:

```
PURPLE_UNSAFE_DEBUG=1 PURPLE_VERBOSE_DEBUG=1 pidgin -d 2>&1 | tee /tmp/pidgin.log 
```

**Comment by richvdh** [comment]
(if you need more support, you can try https://vector.im/beta/#/room/#purple:matrix.org)
