### ISSUE TITLE
purple-matrix cannot detect Chatrooms on Spectrum 2 Via Service Discovery.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [matrix-org/purple-matrix#138]
purple-matrix cannot detect Chatrooms on Spectrum 2 Via XMPP Service Discovery.
As a result of that, the Matrix Plugin is useless with Spectrum 2, can this be addressed?

**Comment by richvdh** [comment]
I'm afraid I have no idea what Spectrum 2 is, but if you're looking for something that integrates with XMPP servers, you'll need to try something else: purple-matrix does not support XMPP.

**Comment by Zombie-Ryushu** [comment]
I do not expect it too. Spectrum2 is an application that uses libpurple modules and relays them to XMPP Clients. The actual problem is that even under just straight Pidgin, Matrix tends to report individual users as chat rooms for some reason.

**Comment by richvdh** [comment]
sounds like https://github.com/matrix-org/purple-matrix/issues/65 then.

In any case, as https://github.com/matrix-org/purple-matrix#update-20220411 says: this project is not under active development.
