### ISSUE TITLE
Question: Is there any alternative to this project?

### ISSUE THREAD

**Issue by wolfteeth** [matrix-org/purple-matrix#142]
I've lately found myself wanting to condense my chat clients into one program--I'm tired of keeping so many different chat clients open on my desktop. Pidgin/libpurple seems like an ideal way to do this, but I was disappointed to see that this Matrix project is abandoned.

Is there any other project attempting Matrix integration with libpurple? Maybe a fork of this one?

**Comment by richvdh** [comment]
Not a question we can answer, I'm afraid.

**Comment by Umeaboy** [comment]
Would this page be of any help?

https://www.libhunt.com/r/purple-matrix
