### ISSUE TITLE
Bitlbee keeps posting connected messages

### ISSUE THREAD

**Issue by rodneyrod** [matrix-org/purple-matrix#31]
Every minute or less in bitlbee, the command channel '&bitlbee' keeps posting the following message:
>	root	matrix - Connected

However the plugin doesn't seem to be disconnecting at all, nor is my internet connection unstable or impacting on the connection.
These messages are filling up the command channel and I think it must be some sort of bug

**Comment by marcelvb** [comment]
Same problem here. Quite annoying since it makes other (useful) info scroll out of the screen and scroll buffer.

**Comment by marcelvb** [comment]
I removed this line from `matrix-connection.c`:
`purple_connection_update_progress(pc, _("Connected"), 2, 3);` (line 121)
and the recurring connected messages are gone.

**Comment by penguin42** [comment]
Interesting; neither Finch nor Pidgin have this problem

**Comment by rodneyrod** [comment]
@marcelvb Thanks for finding what was causing that. If this is unexpected behaviour from Bitlbee then we should send a bug report upstream. If not, then maybe we could add a make flag so Bitlbee users can compile a version of this without the warning?

**Comment by Wilm0r** [comment]
I would guess that Pidgin/Finch just update the UI putting the same text in the place where that text was already displayed? While BitlBee is not really a fullscreen UI so the repetition becomes visible.

It could detect repetition and suppress, which is kinda against the stateless proxy character of the program, but it could be added.

**Comment by marcelvb** [comment]
Workaround for irssi without recompiling purple-matrix:
`/ignore -regexp -pattern matrix.*Connected &bitlbee`
(thanks to @Wilm0r  for the tip)

**Comment by xsteadfastx** [comment]
here the workaround for weechat:

`/filter add matrix_conn_msg *&bitlbee * matrix.*Connected`
