### ISSUE TITLE
Every launch creates a new device on your matrix account

### ISSUE THREAD

**Issue by ara4n** [matrix-org/purple-matrix#36]
I haven't checked whether this is still the case, but can't see any fixes since I last tried it.

This results in a bajillion devices attached to your matrix account, which in turn bogs down device_list propagation.  See https://github.com/matrix-org/matrix-ircd/issues/43 for the equivalent bug for matrix-ircd, and https://github.com/matrix-org/synapse/issues/1977 for fixing device_list propagation.

**Comment by richvdh** [comment]
Fixed by #40, thanks to @EionRobb

**Comment by rodneyrod** [comment]
This bug is persisting for me, I'm using this in Bitlbee so I don't know if that is making a difference.
