### ISSUE TITLE
Apostrophes showing as '&#39;' in chats using Bitlbee

### ISSUE THREAD

**Issue by rodneyrod** [matrix-org/purple-matrix#54]
When people use an apostrophes, ' , they show up in the Bitlbee room as `&#39;` instead.

EDIT: Confirmed this bug is also affecting Pidgin

**Comment by rodneyrod** [comment]
Updated issue to reflect findings.

**Comment by penguin42** [comment]
I'm not seeing it in Pidgin; I tried both from Riot and from Pidgin

**Comment by rodneyrod** [comment]
It more affects Bitlbee, but I did notice this happen in Pidgin a few months ago. Testing with Bitlbee will definitely cause the issue.
