### ISSUE TITLE
Full sync response too long?

### ISSUE THREAD

**Issue by eyenx** [matrix-org/purple-matrix#63]
Hi

It seems like the full_state=1 response on sync can somewhat be too big for libjson to handle. I couldn't connect to my home server for some time. I was always getting the error:

```
DEBUG connection: Connection error on 0x5572707d2fd0 (reason: 0 description: Invalid response from homeserver)
```

After debugging the issue, I saw, that the response body was getting cut by libjson-gllib-dev after exactly 32768 bytes:

```
DEBUG matrixprpl: unable to parse JSON: <data>:1:32769: Parse error: scanner: unterminated string constant
DEBUG matrixprpl: Error (the on_body callback failed) parsing HTTP response HTTP/1.1 200 OK
```

In the outputted JSON I see the cut:

```
... Time: 1.153992877","msgtype":"m.text"},"type":"m.room.message"},{"origin_server_ts":1510138341018,"sender":"@username:mys
662b
erver.net","event_id":"$15101383412865wLIkp:myserver.net...
```

After leaving some rooms, closing some private chats, I could get the full_state=1 sync response under 32kb. I retried to login using purple-matrix and it worked successfully with Pidgin and Bitlbee.

Can the json response of a full_state=1 sync be to big for purple-matrix to handle?

Tested with: 

json-glib 1.4.2-1 on Archlinux
libjson-glib-dev 1.2.8-1 on Ubuntu Artful

**Comment by penguin42** [comment]
Yes it can, but the 32k truncation surprises me - I've seen multi-megabyte responses - I bumped up the limit in matrix_api_sync from 10M to 40M recently (commit 4a1219) because I hit that limit.

**Comment by eyenx** [comment]
Hi

Yes I saw that analyzing your code. Good work btw.

The problem seems to come from our Proxy in front of our Synapse Installation. Connecting from the same bitlbee installation directly to synapse works perfectly. 

I tested a matrix.org connection too. Works perfectly. The issue is not within purple-matrix. I'll close it.

Thanks anyway.
