### ISSUE TITLE
messages sent as black text

### ISSUE THREAD

**Issue by ildar** [matrix-org/purple-matrix#74]
Having no formatting intended but the messages sent as:
> "formatted_body": "<font color=\"#000000\"><body bgcolor=\"#ffffff\">yes, sorry again</body></font>"

That makes people angry as black is unseen on a black background.

**Comment by penguin42** [comment]
Hi ildar,
  Which client are you using - pidgin or something else?

**Comment by ildar** [comment]
Yes, sorry. That's pidgin version 2.12
Linux x86_64

**Comment by penguin42** [comment]
I've seen that once or twice in the past; but not normally, so not been able to track it down.
If it happens for you, can you click on the Font button (bottom left of the chat) and see if any of the items are ticked?

**Comment by ildar** [comment]
I guess you imply formatting button.
I tried to Reset format Burt it didn't change anything.
Please contact me in Matrix in 50 minutes that'll be more productive I guess
.
@ildar:matrix.org

> --
Ildar Mulyukov,
child of God

email: ildar.mulyukov@gmail.com
GoogleTalk: ildar.mulyukov@gmail.com
blog: http://johan-notes.blogspot.com/

**Comment by non-Jedi** [comment]
When I've had this problem, it was usually because I was copy-pasting in text from somewhere else. I don't think there's really a solution here since we probably don't want to strip formatting.

**Comment by penguin42** [comment]
non-Jedi: Yeh but there's something odd going on with copy-pasting but I've not quite put my finger on it.
I know for example if I copy/paste someones nic, pidgin gets stuck in whatever colour that nic happened to be; so I think something is remembering the colour of something copy/pasted - I'm assuming that's a pidgin bug rather than pidgin-matrix specifically.

**Comment by ildar** [comment]
NOT-A-BUG.
@penguin42 is completely right.
Formatting menu had Bg & Fg color set.
This is not reset by Reset Formatting.
This may be set as default in Settings. It was in my case.
Closing. Sorry for the noise.
