### ISSUE TITLE
Windows plugin broken due to Cloudflare change

### ISSUE THREAD

**Issue by rodneyrod** [matrix-org/purple-matrix#78]
The .dll supplied by @EionRobb isn't working any more because of the change, and all attempts by me to try and build the plugin for Windows have failed since it's a finiky toolchain.

Getting a proper Windows build of this off the ground would be great for the project and lower the barrier of entry to people like me who can't get this to build for Windows.

**Comment by EionRobb** [comment]
Whoops, sorry.  I've got [a messed up repo](https://github.com/EionRobb/purple-matrix/) so I missed this change (although the plugin still works fine for me without any updates).  Can you remind me of the commit that fixes this and I'll do a build?

**Comment by rodneyrod** [comment]
Pretty sure it was this commit:
https://github.com/matrix-org/purple-matrix/commit/06ea88ed322401cf12e5d4acc854d4883274363b

**Comment by EionRobb** [comment]
I haven't tried it yet, but give https://eion.robbmob.com/libmatrix.dll a go, it should have all the changes from master merged in now

**Comment by rodneyrod** [comment]
Yep it's all working fine now. Thanks a bunch for that :)
Btw if you libpurple guys have any means of donation I'd be happy to help out.
