### ISSUE TITLE
Unable to connect to matrix.org: SSL Handshake Failed

### ISSUE THREAD

**Issue by johschmitz** [matrix-org/purple-matrix#80]
I tryed to connect to matrix.org with pidgin and I am getting the error:

`Unable to connect to matrix.org: SSL Handshake Failed`

**Comment by ebalda** [comment]
Same here.

**Comment by non-Jedi** [comment]
Y'all are gonna need to provide a lot more details before anyone will be able to help you. What OS are you using? Did you build purple-matrix locally or download it prebuilt from somewhere? What version of pidgin/libpurple are you on? etc.

**Comment by turt2live** [comment]
also some information about what your machines see for a certificate: is the date wrong? wrong CN? whatever running purple doesn't support whatever cert is in use? etc

**Comment by ildar** [comment]
I had this problem and was assisted at `Purple` room in Matrix. You can
seek there

The issue is the crypto algorithms that should be tuned

**Comment by ebalda** [comment]
My pidgin version is the following:
```
$ pidgin --version
Pidgin 2.12.0 (libpurple 2.12.0)
```

I am using Ubuntu 18.04. I installed the purple-matrix with  
```apt-get install pruple-matrix```

**Comment by ildar** [comment]
https://matrix.to/#/!kmYmgsWbCpPxluSwIQ:matrix.org/%241526535156885523FqRgk:matrix.org
-- 
Ildar Mulyukov,
(ΙΧΘΥΣ) child of God

email: ildar.mulyukov@gmail.com
matrix: @ildar:matrix.org
GoogleTalk: ildar.mulyukov@gmail.com
blog: http://johan-notes.blogspot.com/

**Comment by johschmitz** [comment]
Okay, from the matrix thread I figured out that I can add a cipher using the NSS plugin like this
`Tools->Plugins->NSS Preferences`
A cipher that seems to work is
`TLS_AES_256_GCM_SHA384 (0x1303)`
However after that I get another error
`Invalid response from homeserver`
And I am still unable to connect.

**Comment by richvdh** [comment]
ok, so this is more of an issue with the default cipher options in pidgin than a problem in purple-matrix. 

https://developer.pidgin.im/ticket/14668 appears to relate to this.

Anyway, as @johschmitz notes, the workaround is:

> Tools->Plugins->NSS Preferences
A cipher that seems to work is
TLS_AES_256_GCM_SHA384 (0x1303)

(as for your other issue: it is probably unrelated; get a debug log as you reconnect (Help->Debug Window) and seek help in #purple:matrix.org/#matrix-purple on freenode if it doesn't yield any clues)

**Comment by grimmy** [comment]
After some more digging this was actually fixed in pidgin (and libpurple) 2.13.0.

**Comment by ebalda** [comment]
I upgraded to pidgin 2.13.0, but the issue persists.

**Comment by johschmitz** [comment]
Did you delete all the old config files during the update process?

Emilio R. Balda <notifications@github.com> schrieb am Fr., 17. Aug. 2018,
12:33:

**Comment by grimmy** [comment]
@ebalda this is silly, but can you verify via the about box that you're running the correct version?
