### ISSUE TITLE
install : "olm/olm.h: No such file or directory"

### ISSUE THREAD

**Issue by technics303** [matrix-org/purple-matrix#86]
On debian 9 with all the dependencies, when i run "make" the command return : 
 
`matrix-e2e.c:35:21: fatal error: olm/olm.h: No such file or directory`
`#include "olm/olm.h"`
`                 ^`
`compilation terminated.`
`Makefile.common:40: recipe for target 'matrix-e2e.o' failed`
`make: *** [matrix-e2e.o] Error 1`

**Comment by richvdh** [comment]
try building with `make MATRIX_NO_E2E=1`

Looks like the docs could do with an update.

**Comment by technics303** [comment]
Thanks to @richvdh i tried `make MATRIX_NO_E2E=1` and an other error appears : 

```
matrix-room.c:40:20: fatal error: gcrypt.h: No such file or directory
 #include <gcrypt.h>
```
 
I'm not good enough to solve it by my own sorry :( thanks for your help !

**Comment by steils** [comment]
@technics303 seems wrong that even with MATRIX_NO_E2E=1 matrix-room.c still includes gcrypt.h.
I think matrix-room.c shouldn't include this header file at all as it uses no functions from gcrypt. gcrypt is used only in martix-e2e.c. I'll make a trivial patch to fix that.

Thanks for pointing out!

**Comment by steils** [comment]
Done https://github.com/matrix-org/purple-matrix/pull/87
