### ISSUE TITLE
Make errors on Debian 9

### ISSUE THREAD

**Issue by joshfleming** [matrix-org/purple-matrix#89]
I attempted to build from source on Debian 9. I was able to get the build to happen, but it required a lot of modifications to the Makefile.common and packages not listed in the readme.md

Some of this is due to libraries not being available in debian 9, but most of these are libraries just not being found that are installed. Also let me know if there's a better way, or if perhaps there's a debian 9 package that contains olm.h

I received various file not found errors prompting me to locate those library files and include them directly. And installing libsqlite3-dev, libolm-dev & libgcrypt20-dev

In the end I used these steps to complete the build:
```shell_script
sudo apt install -y libpurple-dev libjson-glib-dev libhttp-parser-dev libglib2.0-dev sqlite3 libsqlite3-dev libgcrypt20-dev
```
Download and Install libolm2 and libolm2dev, not available in Debian 9, these are from the unstable (sid) repo.
```shell_script
wget http://ftp.us.debian.org/debian/pool/main/o/olm/libolm-dev_2.2.2+git20170526.0fd768e+dfsg-1_amd64.deb
wget http://ftp.us.debian.org/debian/pool/main/o/olm/libolm2_2.2.2+git20170526.0fd768e+dfsg-1_amd64.deb
sudo dpkg -i libolm2_2.2.2+git20170526.0fd768e+dfsg-1_amd64.deb
sudo dpkg -i libolm-dev_2.2.2+git20170526.0fd768e+dfsg-1_amd64.deb
```
Modify line 9 of Makefile.common to be:
`CPPFLAGS += -MMD -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libpurple -I/usr/include/json-glib-1.0`

Clone purple-matrix, make, sudo make install
```shell_script
git clone https://github.com/matrix-org/purple-matrix
cd purple-matrix/
make
sudo make install
```

**Comment by Half-Shot** [comment]
Thanks for the detailed instructions, I'm quite shocked that olm was needed at all to make this work (though probably to get rid of the nag line).

I suspect that node-purple should have it's make process updated to work (and we should test on deb9)

**Comment by denics** [comment]
Thanks @joshfleming , I would like to add that, in Debian 10, you should simply add:

```
sudo apt install libolm-dev
```

to your guide.

**Comment by penguin42** [comment]
Yep, you need your libolm, however as the readme says, you can configure without E2E with make MATRIX_NO_E2E=1
